services:
  # Hardhat Node - Local Ethereum development network
  hardhat-node:
    image: node:20-alpine
    container_name: confidential-game-hardhat
    working_dir: /app
    command: npx hardhat node --hostname 0.0.0.0
    ports:
      - "8545:8545"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - game-network

  # Mock Gateway - Simulates FHE Gateway for local testing
  mock-gateway:
    build:
      context: ./docker/mock-gateway
      dockerfile: Dockerfile
    container_name: confidential-game-gateway
    ports:
      - "7077:7077"
    environment:
      - PORT=7077
      - NODE_ENV=development
      - DEBUG=gateway:*
    networks:
      - game-network
    depends_on:
      - hardhat-node

  # Contract Deployer - Deploys contracts once network is ready
  deployer:
    image: node:20-alpine
    container_name: confidential-game-deployer
    working_dir: /app
    command: sh -c "sleep 15 && npm run deploy:local"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - game-network
    depends_on:
      - hardhat-node
      - mock-gateway

  # Relayer - Manages game operations
  relayer:
    image: node:20-alpine
    container_name: confidential-game-relayer
    working_dir: /app
    command: sh -c "sleep 25 && node scripts/relayer.js"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - GATEWAY_URL=http://mock-gateway:7077
      - GAME_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
    networks:
      - game-network
    depends_on:
      - deployer
    restart: unless-stopped

networks:
  game-network:
    driver: bridge
